### PR TITLE
Added about Sir Syed Ahmad Khan Page

### LINKED ISSUE #63: Add about Sir Syed Ahmad Khan section
Refer slide 14

### PR DESCRIPTION
**Pull request by sneha-chauhan**
Added About Sir Syed button link in Apply Section
Added About Sir Syed Ahmad Khan Section 
 - [ ] Closes #63 
Screenshot (54)

---

Screenshot (55)

### CODE REVIEW

**Comment by pnijhara** [comment]
@himanshuvarandani can you take a look at this? I think @sneha-chauhan is facing some issues on this PR.

**Comment by himanshuvarandani** [comment]
Ok, I will try to resolve

**Comment by himanshuvarandani** [comment]
@sneha-chauhan Make sure to resolve conflicts (if any) when you are merging main branch to your branch before making a commit and make seperate commit for your changes with correct commit name.

**Comment by himanshuvarandani** [comment]
@pnijhara Now, you can review this pr and merge.

**Review by pnijhara — APPROVED** [review]

**Pull request merged**
