### PR TITLE
[WIP] Adds Datetable component

### PR DESCRIPTION
**Pull request by sanjana-302**
---

## PR description

- Adds Datetable component
- Adds global font (Railway)
- Basic layout for further components

### CODE REVIEW

**Comment by sanjana-302** [comment]
Screenshots - 
Screenshot from 2021-08-12 14-07-21
Screenshot from 2021-08-12 13-54-28

**Review by pnijhara — COMMENTED** [review]
Ya, that looks good to me. However, I cannot understand the issue pointed by DeepSource.

**Comment by sanjana-302** [comment]
Yeah, Just going through them.

**Comment by pnijhara** [comment]
@roshnet @prateekj117 can you look at these issues pointed out by DeepSource? These are mostly style-related issues. I think they can be ignored. What do you say?

**Comment by roshnet** [comment]
@pnijhara Do we have an option to specify ESLint rules for DeepSource? Warnings 1 and 2 are ESLint warnings and can be disabled from there (also they are opinionated warnings, so no real issues).

For warning 3, I agree as a uniform syntax (i.e. either `const App = () => {}` or `export default function App()`) is always better than a mixed one.

Warnings 4 too should not be ignored (eslint editor plugin could sort most of them out locally).

Warning 5 does not apply to Next.js as it doesn't require importing React, so can simply be ignored. Maybe there's an option in DeepSource to disable that specific check in the future, since it's always gonna show up.

**Comment by pnijhara** [comment]
I am not sure about the ESLint rules. I have to read the documentation for that. But as far as I know, they can be removed. And I agree with your comment on warnings 3 and 4. @roshnet should @sanjana-302 keep this PR merged and work on a different PR or does she needs to revert this one?

**Comment by roshnet** [comment]
I think it's fine. A fix could be added later!

**Pull request merged**
