### PR TITLE
Updated the textual CSS of About File

### PR DESCRIPTION
**Pull request by sneha-chauhan**
Screenshot (48)

## Updated About.js
Modified  textual CSS of About file
fix #49

### CODE REVIEW

**Comment by himanshuvarandani** [comment]
@sneha-chauhan PR is good but it will be better if you decrease padding of container and make heading size to be responsive.
I am attaching the screenshot of problem

image

**Comment by sneha-chauhan** [comment]
* Made the heading responsive
* Decrease the padding of container 
Screenshot (50)

**Comment by himanshuvarandani** [comment]
@sneha-chauhan Make sure to check this on all sizes. This problem still exists on mobile phone
image

Heading problem also exist on large screen
image


Suggesstions:
- Can remove "h-14" from heading which will fix the issue of heading
- Can fix the margin to mx-8 or mx-12 or mx-16 instead of mx-28
- Can change the size of paragraph to text-sm for small screen (<sm)

**Comment by himanshuvarandani** [comment]
> * Made the heading responsive
> * Decrease the padding of container
>   Screenshot (50)

Yeah it is looking fine, you can push changes I will check again.

**Comment by maaz-bin-asad** [comment]
Looks fine to me 
@pnijhara . Please merge if it's okay from your side.

**Comment by himanshuvarandani** [comment]
@maaz-bin-asad I think changes are not pushed yet.

**Comment by pnijhara** [comment]
@himanshuvarandani please help @sneha-chauhan and get it merged before the EOD.

**Comment by himanshuvarandani** [comment]
@pnijhara Yeah I am working on that

**Comment by pnijhara** [comment]
@sneha-chauhan Why have you deleted this PR?
This could have saved us a lot of time.

**Pull request closed without merging**
